### ISSUE TITLE
[Proposal] Optimistic ZK connections

### ISSUE THREAD

**Issue by zhengyangfeng00** [open-ibc/vibc-core-smart-contracts#11]
## Background

The objective is to decrease the gas cost of verifying ibc related messages. For additional background, refer to the design document [ADR 10 Optimistic ZK Connections](https://www.notion.so/cb54af27d51345fa8ede6c5020566b67?pvs=21). This issue aims to discuss the implementation level design, focusing on the modifications that need to be made on the vibc core SC side.

### Terms

- **Non-Optimistic consensus state**: This is a subset of the block header that includes the public keys of all active validators, as well as their voting power and other relevant information.
- **Optimistic consensus state**: This is the Merkle root of the Polymer chain's state. It can be used to perform inclusion proofs for any key-value pairs stored on the Polymer chain. The Op consensus state is part of the Non-Op consensus state.
- **Client update**: This refers to updating the Polymer chain's consensus state. There are two types of client updates:
    - Updating the non-OP consensus state: The non-OP consensus state can be verified on-chain and is considered trusted immediately after passing the on-chain verification.
    - Updating the OP consensus state: The OP consensus state is buffered and not verified on-chain. Instead, it relies on watchers to perform off-chain fraud detection. Once the fraud proof window has passed, the OP consensus state is considered trusted and can be used to perform inclusion proof for data packets.
- **Packet verification**: This refers to using Merkle proof to verify the existence of an IBC data packet in relation to a consensus state at a specific height, among other things.
- **Watcher**: This component is responsible for checking for fraudulent client updates or fraudulent data packets.
- **Updater**: This component is an off-chain process that performs client updates periodically. Its purpose is to ensure that the non-op consensus state of the vIBC core SC is not more than one bounding period older than the latest block on the Polymer chain.

There are two approaches for implementing the optimisitc packet routing, with different pros and cons.

### High level

There are 4 roles in the client state update process:

- the relayer
- the watcher
- the vibc core SC
- the polymer chain

The interactions between these components can be illustrated with the diagram below:

<img width="1124" alt="image" src="https://github.com/open-ibc/vibc-core-smart-contracts/assets/1428290/7e33207c-bd09-4d1b-86d4-62de203c150b">

The sequence diagram above describes two different cases:

**Case 1: Relaying a data packet when fraud is not detected**

1. The relayer sends an Op consensusState update to the smart contract. The vIBC core smart contract saves the Op consensusState in its internal state and waits for the fraud proof window for the state to pass.
2. The vIBC core SC emits an UpdateClient event with the Op consensusState. The event is received by the watcher and verified. In this case, the watcher finds that the Op consensus state matches what it receives from Polymer validators.
3. The relayer waits until the fraud proof window has passed, and then sends data packets included in the Op consensus state to the vIBC core SC.
4. The vIBC Core SC receives the data packets and performs packet verification. This includes:
    1. Verifying that the Op consensus state containing the data packets has passed the fraud proof window and is now considered trusted.
    2. Performing a Merkle proof for the data packets against the Op consensus state to verify their existence on the Polymer chain. Note, this operation is not cheap and can cost between 30k - 60k gas.
5. Once the packet verification passes, the vIBC core SC passes the data packet to the user's dAPP.
6. Relaying a data packet and fraud is detected.

**Case 2: Relaying a data packet when fraud is detected**

1. The relayer sends an Op consensusState update to the smart contract. The vIBC core smart contract saves the Op consensusState in its internal state and waits for the fraud proof window for the state to pass.
2. The vIBC core SC emits an UpdateClient event with the Op consensusState. The event is received by the watcher and verified. In this case, the watcher finds that the Op consensus state *doesn’t match* what it receives from Polymer validators.
3. The watcher constructs a ZKP using zkmint to prove that a different Op consensusState should be the correct one. It sends the ZKP to the vIBC core SC using the `submitFraudProof` method.
4. The vIBC core SC receives the fraud proof and verifies it. *To verify the proof, the vIBC core SC needs a non-op consensus state that is within a bounded time period from the op consensus state that the proof attempts to prove as fraudulent. The updater component ensures that the non-op consensus state is within a bounded time period from the latest block on the Polymer chain.*
5. After the vIBC core SC verifies the fraud proof, it emits a SubmitFraudProof event. This event is received by the Polymer chain, where the relayer who sent the fraudulent packet is slashed.

Pros:

- The vIBC core SC doesn't need to buffer data packets within the fraud proof window. During high traffic, there might be a lot of data packets that need to be buffered, and the cost of storing them in the SC's state can be expensive and unbounded.

Cons:

- Packet verification needs to be done on-chain, which is an expensive operation.

## Alternative approach considered: Smart contract bypasses packet verification

This approach is similar to Approach 1, with the major difference being that the relayer sends out the data packets immediately after updating the op consensus state on the vIBC core SC. Alternatively, the relayer can send data packets with the op consensus state.

The data packets are buffered in the internal state of the vIBC core SC. During the fraud proof window, watchers not only verify the op-consensus state but also verify the data packets. The packet verification logic is the same as in Approach #1 but is done off-chain to save gas costs, at the cost of buffering the data packets during the fraud proof window.

In addition to buffering messages in the internal state of the vIBC core SC, the relayer must periodically call the flush method of the SC. This triggers the vIBC core SC to pass data packets outside the fraud-proof window to the user's dApp. Note that this operation incurs gas costs.

The reason this approach is not preferred is because the extra gas cost of message buffering and making calls to the flushing method is unbounded and hard to predict. The additional cost may not offset the gas savings achieved by performing packet verification off-chain. Moreover, Approach 1 is more straightforward than this approach. Therefore, we believe that Approach 1 is a better starting point. We can revisit the design once the system is live and we have a better understanding of the traffic.

## Out of scope discussions

The following design items will be deferred to later design discussions:

- Determining the amount to be slashed when fraud is detected
- Deciding how the "fraud detected" message will be communicated to users' dApps

**Non-optimisitc packet routing**

It is possible for a packet sender to update the vIBC core SC’s op consensus state with a proof, and send data packets included in the op consensus state. 

In this case, the vIBC core smart contract will perform packet verification. If the verification passes, the packet is immediately forwarded to the user's dApp without waiting for the fraud proof window.

The sender experiences lower latency and lower security risks, since there is no optimistic component and the packet relaying is safe even if no watcher is running. However, this comes at the cost of higher transaction costs.

The implementation is possible, but it is outside the scope of this issue.

**Comment by zhengyangfeng00** [comment]
Alternative design choices:

- Instead of staking on the polymer chain, relayers can stake tokens on the Ethereum chain. When misbehavior is detected, the staked Ethereum tokens are slashed.
- Instead of using ZkMint to generate fraud proofs, a standard Tendermint client update verification mechanism can be implemented and used with ETH. Since fraudulent client state update messages occur rarely, the extra gas cost of using Tendermint client update verification instead of ZkMint is not significant.

**Comment by zhengyangfeng00** [comment]
updated the design based mainly on @qinlz2 's idea

**Comment by Inkvi** [comment]
How can the vIBC core SC perform this action `Slash the relayer's account`? It would only be possible if the staking happens on the same contract or the contract is given access to slash when staking happens on another contract. But it will only be possible if staking happens on eth side. For polymer staking, I would assume that the SC needs to emit an event and someone who controls the staking needs to listen for such events. And that can't be a relayer because if they misbehave they can omit the event form being communicated if it's going to prevent them being slashed.

**Comment by notbdu** [comment]
> If the client update message comes from the fraud provider, it has a zero-knowledge proof (ZKP) to invalidate a previously applied state update. The client update is applied, and the emitted event includes extra fields that allow the polymer chain to slash the relayer's account.

The relayer can be a fraud prover. Wouldn't be a separate thing IMO. The relayer can either embed proof generation natively or talk to an external proving service. 

> The vibc core SC accepts IBC data packets from relayers, without verifying the messages.
It buffers the received messages in memory
Periodically it receives a tick message from relayers to flush the IBC packets outside the fraud proof window

There's no concept of persistent memory across transactions when it comes to smart contracts. If you wanted to take an approach of not needing to verify an inclusion proof of each packet (in the state root) on execution, you could 

> It listens to the EVM chain for the RecvPacket event and verifies if the packet is included in the Polymer chain. If the packet is not found:

The fraud prover should be looking for a mismatching client update (updated state root does not match polymer state root). Packets are 

> Instead of staking on the polymer chain, relayers can stake tokens on the Ethereum chain. When misbehavior is detected, the staked Ethereum tokens are slashed.

This was Nomad's model for slashing. This does not scale to many chains. Cost of capital also makes this approach ineffective. Better to reuse existing stake on Polymer.

> Instead of using ZkMint to generate fraud proofs, a standard Tendermint client update verification mechanism can be implemented and used with ETH. Since fraudulent client state update messages occur rarely, the extra gas cost of using Tendermint client update verification instead of ZkMint is not significant.

An optimized tendermint light client algo in solidity would be approx 5m gas. ZK proof verification is still much better at 300k gas. Also needs to be used for validity.

**Comment by zhengyangfeng00** [comment]
> How can the vIBC core SC perform this action `Slash the relayer's account`? It would only be possible if the staking happens on the same contract or the contract is given access to slash when staking happens on another contract. But it will only be possible if staking happens on eth side. For polymer staking, I would assume that the SC needs to emit an event and someone who controls the staking needs to listen for such events. And that can't be a relayer because if they misbehave they can omit the event form being communicated if it's going to prevent them being slashed.

Yes, the design I posted assumes staking on ETH side. However as @notbdu mentioned the capital cost would be too high and doesn't scale to multiple chains. I'm going to modify the design to do staking on Polymer chain side.

**Comment by dshiell** [comment]
> How can the vIBC core SC perform this action `Slash the relayer's account`? It would only be possible if the staking happens on the same contract or the contract is given access to slash when staking happens on another contract. But it will only be possible if staking happens on eth side. For polymer staking, I would assume that the SC needs to emit an event and someone who controls the staking needs to listen for such events. And that can't be a relayer because if they misbehave they can omit the event form being communicated if it's going to prevent them being slashed.

I think we could assume at least one benign relayer? So even if a bad relayer refused to send events, if at least one other relayer does then fraud can be proven?

**Comment by zhengyangfeng00** [comment]
> > How can the vIBC core SC perform this action `Slash the relayer's account`? It would only be possible if the staking happens on the same contract or the contract is given access to slash when staking happens on another contract. But it will only be possible if staking happens on eth side. For polymer staking, I would assume that the SC needs to emit an event and someone who controls the staking needs to listen for such events. And that can't be a relayer because if they misbehave they can omit the event form being communicated if it's going to prevent them being slashed.
> 
> I think we could assume at least one benign relayer? So even if a bad relayer refused to send events, if at least one other relayer does then fraud can be proven?

In addition to that, the relayer that relays message from ETH -> Polymer and Polymer -> ETH are two different relayers. In the scenario we are discussing, the Polymer -> ETH is the fraudulent relayer and ETH -> Polymer relayer is responsible for relaying fraud proof to Polymer chain for slashing.
