### ISSUE TITLE
[discuss] portId address matching logic

### ISSUE THREAD

**Issue by zhengyangfeng00** [open-ibc/vibc-core-smart-contracts#32]
## Problem

When the core smart contract (SC) receives a packet, it checks the address within the `portIdAddressMatch` function:

```
    function portIdAddressMatch(address addr, string calldata portId) public view returns (bool) {
        if (keccak256(abi.encodePacked(portPrefix)) != keccak256(abi.encodePacked(portId[0:portPrefixLen]))) {
            return false;
        }
        string memory portSuffix = portId[portPrefixLen:];
        return hexStrToAddress(portSuffix) == addr;
    }

```

The core SC is created with a fixed portPrefix. When it receives a packet with port id `polyibc.eth1.D5724171C2b7f0AA717a324626050BD05767e2C6`, it compares the prefix with the prefix of the port. If we set the prefix to be `polyibc.`, then it compares this prefix with `polyibc.`. In this case, they match.

However, the function then compares the actual address with the remaining part of the port id (i.e., `portId[len(prefix):]`). In this case, it compares `eth1.D5724171C2b7f0AA717a324626050BD05767e2C6` with `D5724171C2b7f0AA717a324626050BD05767e2C6`, resulting in a mismatch.

## Proposed Solution

We propose to fix the length of the chain name to 4. In the comparison step, we would then compare `portId[13:]` with the address rather than `portId[len(prefix):]`.

## Alternative Solution

An alternative approach would be to split the portId by "." and use the last part as the address. However, implementing this in Solidity is a) ugly, b) has extra gas cost, c) increase the code size of the contract.

**Comment by dshiell** [comment]
addr looks like `eth1.D5724171C2b7f0AA717a324626050BD05767e2C6`?

**Comment by dshiell** [comment]
Can we compute the len difference between addr and portSuffix as hex to find the client prefix offset?

**Comment by zhengyangfeng00** [comment]
the current logic should work if we set the prefix to be `polyibc.eth1` on the first chain and `polyibc.eth2` on the second chain. closing.
